# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17a23ef38d078d2124c730b2b9181e565b3e147692e5d3c58aed5942d2706a31a8b540f7582f0666eb7ab3aa07f0558c58245c0b52063342ee25a0d9e1e172dd

test:
  secret_key_base: 157c5bb256cc82b13847168266ff28d2e5a4b13f2289d373675bddbb4b39219f8f02e5849332cc1c08d8b9bff65a84f3c74cc94978d8f2144a4012390920ae7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
